const CHANGE_SEX = "CHANGE_SEX";
const CHANGE_COLOR = "CHANGE_COLOR";
const OPEN_SIDEBAR = "OPEN_SIDEBAR";
const SET_PRODUCTS = "SET_PRODUCTS";
const MODAL_HANDLER = "MODAL_HANDLER";
const SHOW_ORDER = "SHOW_ORDER";
const SET_COLORS = "SET_COLORS";
const SET_SIZES = "SET_SIZES";
const SHOW_SIZES = "SHOW_SIZES";
const SET_ORDER_SIZES_BY_COLOR = "SET_ORDER_SIZES_BY_COLOR";
const CLEAR_ORDER = "CLEAR_ORDER";
const GET_PRICE = "GET_PRICE";
const ADD_TO_BASKET = "ADD_TO_BASKET";
const CHANGE_PREVIEW_COLOR = "CHANGE_PREVIEW_COLOR";
const CHANGE_BASKET_ORDER = "CHANGE_BASKET_ORDER";
const UPDATE_BASKET_ORDER = "UPDATE_BASKET_ORDER";
const ACTIVE_MODAL = "ACTIVE_MODAL";
const SET_ORDER_FROM_BASKET = "SET_ORDER_FROM_BASKET";
const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
const REMOVE_ORDER_BY_COLOR = "REMOVE_ORDER_BY_COLOR";
const OPEN_CONFIRM = "OPEN_CONFIRM";
const ACTIVE_SIDEBAR = "ACTIVE_SIDEBAR";
const ORDER_IS_CHANGED = "ORDER_IS_CHANGED";
const OPEN_CONTACT_MODAL = "OPEN_CONTACT_MODAL";

const SELECT_SUBREDDIT = "SELECT_SUBREDDIT";
const INVALIDATE_SUBREDDIT = "INVALIDATE_SUBREDDIT";
const REQUEST_PRODUCTS = "REQUEST_PRODUCTS";
const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
const REQUEST_COLORS = "REQUEST_COLORS";
const RECEIVE_COLORS = "RECEIVE_COLORS";
const REQUEST_SIZES = "REQUEST_SIZES";
const RECEIVE_SIZES = "RECEIVE_SIZES";
const SET_ADDITIONAL_COLORS = "SET_ADDITIONAL_COLORS";

const SET_PRODUCT = "SET_PRODUCT";

const SAVE_ORDER_CHANGES = "SAVE_ORDER_CHANGES";


export {
  CHANGE_SEX,
  CHANGE_COLOR,
  OPEN_SIDEBAR,
  SET_PRODUCTS,
  MODAL_HANDLER,
  SHOW_ORDER,
  SET_COLORS,
  SET_SIZES,
  SHOW_SIZES,
  SET_ORDER_SIZES_BY_COLOR,
  CLEAR_ORDER,
  GET_PRICE,
  ADD_TO_BASKET,
  SELECT_SUBREDDIT,
  INVALIDATE_SUBREDDIT,
  REQUEST_PRODUCTS,
  RECEIVE_PRODUCTS,
  REQUEST_COLORS,
  RECEIVE_COLORS,
  CHANGE_PREVIEW_COLOR,
  REQUEST_SIZES,
  RECEIVE_SIZES,
  CHANGE_BASKET_ORDER,
  ACTIVE_MODAL,
  SET_ORDER_FROM_BASKET,
  UPDATE_BASKET_ORDER,
  SET_PRODUCT,
  SET_ADDITIONAL_COLORS,
  REMOVE_ORDER_BY_COLOR,
  SAVE_ORDER_CHANGES,
  OPEN_CONFIRM,
  ACTIVE_SIDEBAR,
  ORDER_IS_CHANGED,
  OPEN_CONTACT_MODAL,
  REMOVE_FROM_BASKET
};
